CREATE DATABASE pproject-83;

CREATE TABLE urls (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255),
    created_at timestamp
);

CREATE TABLE url_checks (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    url_id bigint REFERENCES urls (id),
    status_code bigint,
    h1 varchar(255),
    title varchar(255),
    description varchar(255),
    created_at timestamp
);