name: GitHub Actions
run-name: ${{ github.actor }} mew mew
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - run: echo "🍏 This job's status is ${{ job.status }}."
